name: Build for Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup OS
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-multilib

    - name: Checkout source
      uses: actions/checkout@v4
      
    - name: Build source
      run: |
        cd build/linux/
        sh build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: empty-pkcs11-linux
        path: build/linux/empty-pkcs11-*.so
